Feature/tour filters
AlgorBerunDev/tavakkalna pull request #17
Opened 2024-02-11 19:21 UTC by NuraliAKH

filterla tayyor

2024-02-11 23:32 UTC, AlgorBerunDev requested changes

2024-02-11 23:32 UTC, AlgorBerunDev commented on backend/src/app.module.ts
> +  controllers: [AppController, TariffController],
TariffModule ni yaratib o'shani imports: [TariffModule] ga qilib qo'y. app.module.ts ga controller va servicelarni to'g'ridan to'g'ri import qilma

2024-02-11 23:32 UTC, AlgorBerunDev commented on backend/src/app.module.ts
> +    TariffService,
Bu ham shunday TariffService TariffModuleni ichida bo'ladi. TariffModule esa AppModule ni ichida imports ga qo'shiladi

2024-02-11 23:32 UTC, AlgorBerunDev commented on backend/src/modules/auth/auth.controller.ts
> +  @Roles(Role.MasterManager)
Nima uchun bularni joyini almashtirib qo'yding?

2024-02-11 23:32 UTC, AlgorBerunDev commented on backend/src/modules/tariff/dto/tariff.dto.ts
> +export class CreateTariffDto {
create-tariff.dto.ts update-tariff.dto.ts qilib qo'y. Biz shu struktura bo'yicha ishlaymiz. xar bir Dto bitta file ichida bo'lishi kerak, sababi dtolar ro'yxati dto direktoriyada  ochganda ko'rinishi kerak bu qidirishni osonlashtirad

2024-02-11 23:32 UTC, AlgorBerunDev commented on backend/src/modules/tariff/tariff.controller.ts
> +@Controller('tariffs')
controllerdan oldin empty line qo'sh ya'ni enter tashlab qo'y

2024-02-11 23:32 UTC, AlgorBerunDev commented on backend/src/modules/tariff/tariff.module.ts
> +@Module({
mana yaratgan ekansanku nega shuni AppModulega import qilmading?

2024-02-11 23:32 UTC, AlgorBerunDev commented on dashboard/src/utils/axios.ts
> +  baseURL: "http://localhost:8081/",
buni envirementdan o'qib olsin, sababi CI/CDda nastroy qilish qiyin buni enviromentga qo'shib qo'yib o'sha orqali ishlat

2024-02-12 12:21 UTC, NuraliAKH commented
boldi

2024-02-14 09:06 UTC, AlgorBerunDev approved these changes

2024-02-14 10:00 UTC, merged